// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQllf5D_q5kA4PJq_sJG937bDHjmAy-R4',
    appId: '1:526961461411:web:686fd5752f5a9ec891d716',
    messagingSenderId: '526961461411',
    projectId: 'fotofusion-53943',
    authDomain: 'fotofusion-53943.firebaseapp.com',
    storageBucket: 'fotofusion-53943.appspot.com',
    measurementId: 'G-HYX0WKD9EB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6Ql1r55lx8VhoN7YgKaaHLP4Cb7dLuIY',
    appId: '1:526961461411:android:d122043bd746185591d716',
    messagingSenderId: '526961461411',
    projectId: 'fotofusion-53943',
    storageBucket: 'fotofusion-53943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmD7GB9a3bfGYC5_6kTH-bB8Ey1cjwAQQ',
    appId: '1:526961461411:ios:e72a7c4ecc26a18691d716',
    messagingSenderId: '526961461411',
    projectId: 'fotofusion-53943',
    storageBucket: 'fotofusion-53943.appspot.com',
    iosBundleId: 'com.example.fotofusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmD7GB9a3bfGYC5_6kTH-bB8Ey1cjwAQQ',
    appId: '1:526961461411:ios:93ba2d053232244691d716',
    messagingSenderId: '526961461411',
    projectId: 'fotofusion-53943',
    storageBucket: 'fotofusion-53943.appspot.com',
    iosBundleId: 'com.example.fotofusion.RunnerTests',
  );
}
